## 자바스크립트 에러와 에러 처리

자바스크립트의 예외를 처리하는 구문은 "throw"와 "try~catch~finally" 

### throw
에러 상황이라고 판단될 경우 강제로 예외 오류를 발생시키고 코드 실행을 종료하는 구문.
사용자가 코드상에 직접 원하는 위치에 예외 오류를 발생시키고 실행을 중지하는데 사용한다.

```javascript
throw '사용자 지정 에러 메세지'
```

이렇게 작성하면 해당 위치에서 코드 실행은 멈추게 되고, 사용자가 지정한 에러 메세지를 표시하는 예외 오류가 발생한다.

```javascript
function myFunc(param){
  throw '사용자 지정 에러 메세지'
  console.log(param + ' run!');
}
myFunc('myFunc');
```
이렇게 예외 오류를 발생시키는 함수를 실행하면 예외 오류를 발생시킨 throw 구문에서 코드 실행은 멈추고 그 밑의 콘솔 로그 출력은 실행되지 않는다.


### try~catch~finally
에러가 발생할 가능성이 있는 코드 블록을 감싸서, 에러가 발생할 경우 catch블록에서 발생한 에러에 대한 대응을 할 수 있도록 한다. 그리고, 예외 발생 여부와는 무관하게 무조건 실행되도록 하는 코드를 finally 블록에 추가할 수 있다.

예를 들어 파일을 읽어서 처리하는 코드 블록을 try블록에 넣어서 실행하다 에러 메시지 내용을 담은 message 속성을 통해 에러의 원인을 알아낼 수 있다.

try 블록에서 처리가 정상 완료되거나, catch 블록에서 에러 처리를 한 후에는 finally 블록에 넣은 파일을 닫는 코드가 무조건 실행된다.

가상 코드로 try~catch~finally 코드 구조를 작성하면 다음과 같다.

```javascript
let fo = openFile();
try {
  fo.readFile();
} catch(ex){
  console.log(ex.message)
} finally {
  if(fo){ // 파일 객체가 존재하는지 먼저 체크
    fo.close();
  }
}
```
읽기/쓰기 위해서 연 파일은 반드시 닫아야 한다.

닫지 않고 코드를 종료할 경우 파일이 열린 상태이기 때문에 파일이 잠겨서(lock) 다음 번 실행할 때 파일을 읽을 수 없게 된다.

이런 문제를 미연에 방지하기 위해, 무조건 실행되는 finally 블록에 파일을 닫는 코드를 넣어 코드의 안정성을 끌어올릴 수 있다.
실제로 예외처리 하지 않은 코드 블록으로 파일을 읽다 보면 파일이 잠겨서 웹 브라우저를 강제 종료 해야하는 경우가 종종 발생한다.

무조건 실행되는 코드 블록이 필요하지 않은경우 finally 블록은 생략할 수 있다.
간단하게 에러를 발생시켜 try~catch~finally가 어떤 식으로 동작하는지 웹 브라우저에서 확인해 본다.

### try~catch 예외처리 예

```javascript
const a = 0;
try{
  console.log(b)// b가 정의되지 않아서 에러를 발생함
} catch(error){
  console.log(error.message); //b is not defined 메세지를 콘솔에 출력
} finally {
  console.log(a) // a의 값을 무조건 출력한다.
}
```